export interface Scholarship {
  id: string;
  name: string;
  sponsoringOrg: string;
  amount: number;
  amountLabel: string;
  category: ('SC' | 'ST' | 'OBC' | 'General' | 'EWS' | 'All')[];
  gender: 'All' | 'Female' | 'Male';
  state: string;
  minMarks: number;
  maxIncome: number;
  classLevel: ('9' | '10' | '11' | '12' | 'UG' | 'PG' | 'All')[];
  deadline: string;
  description: string;
  eligibility: string[];
  applyUrl: string;
  tags: string[];
  isNational: boolean;
}

export const scholarships: Scholarship[] = [
  {
    id: 'nsp-sc-post',
    name: 'Post-Matric Scholarship for SC Students',
    sponsoringOrg: 'Ministry of Social Justice & Empowerment, GoI',
    amount: 50000,
    amountLabel: '₹50,000/year',
    category: ['SC'],
    gender: 'All',
    state: 'All',
    minMarks: 50,
    maxIncome: 250000,
    classLevel: ['11', '12', 'UG', 'PG'],
    deadline: '2026-10-31',
    description: 'Central government scholarship for SC students pursuing post-matric education. Covers tuition fees, maintenance allowance, and study materials.',
    eligibility: ['SC category', 'Family income < ₹2.5L/yr', 'Recognized institution', 'Min 50% marks'],
    applyUrl: 'https://scholarships.gov.in',
    tags: ['Central Govt', 'Post-Matric', 'Full Support'],
    isNational: true,
  },
  {
    id: 'nsp-st-post',
    name: 'Post-Matric Scholarship for ST Students',
    sponsoringOrg: 'Ministry of Tribal Affairs, GoI',
    amount: 50000,
    amountLabel: '₹50,000/year',
    category: ['ST'],
    gender: 'All',
    state: 'All',
    minMarks: 50,
    maxIncome: 250000,
    classLevel: ['11', '12', 'UG', 'PG'],
    deadline: '2026-10-31',
    description: 'Central scholarship for ST students to encourage higher education among tribal communities.',
    eligibility: ['ST category', 'Income < ₹2.5L/yr', 'Regular student in recognized institution', 'No other govt. scholarship'],
    applyUrl: 'https://scholarships.gov.in',
    tags: ['Central Govt', 'Tribal', 'Post-Matric'],
    isNational: true,
  },
  {
    id: 'nsp-obc-post',
    name: 'Post-Matric Scholarship for OBC Students',
    sponsoringOrg: 'Ministry of Social Justice & Empowerment, GoI',
    amount: 30000,
    amountLabel: '₹30,000/year',
    category: ['OBC'],
    gender: 'All',
    state: 'All',
    minMarks: 50,
    maxIncome: 100000,
    classLevel: ['11', '12', 'UG', 'PG'],
    deadline: '2026-11-15',
    description: 'Scholarship for OBC students at post-matric level to boost educational attainment in Other Backward Classes.',
    eligibility: ['OBC (Central List)', 'Income < ₹1L/yr', 'Recognized institution', 'Min 50% marks'],
    applyUrl: 'https://scholarships.gov.in',
    tags: ['Central Govt', 'OBC', 'Post-Matric'],
    isNational: true,
  },
  {
    id: 'nsp-minority',
    name: 'Pre & Post-Matric Minority Scholarship',
    sponsoringOrg: 'Ministry of Minority Affairs, GoI',
    amount: 25000,
    amountLabel: '₹25,000/year',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 50,
    maxIncome: 200000,
    classLevel: ['9', '10', '11', '12', 'UG', 'PG'],
    deadline: '2026-10-15',
    description: 'Scholarship for students from minority communities (Muslim, Christian, Sikh, Buddhist, Parsi, Jain).',
    eligibility: ['Minority community', 'Min 50% marks', 'Income < ₹2L/yr', '30% seats reserved for girls'],
    applyUrl: 'https://scholarships.gov.in',
    tags: ['Minority', 'Central Govt', 'All Levels'],
    isNational: true,
  },
  {
    id: 'inspire',
    name: 'INSPIRE Scholarship for Higher Education',
    sponsoringOrg: 'Department of Science & Technology, GoI',
    amount: 80000,
    amountLabel: '₹80,000/year',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 90,
    maxIncome: 999999999,
    classLevel: ['UG', 'PG'],
    deadline: '2026-09-30',
    description: 'For top students pursuing Natural and Basic Sciences. One of India\'s most prestigious science scholarships.',
    eligibility: ['Top 1% in Class 12 board', 'BSc/BS/Int. MSc in Natural Sciences', 'Not Engineering/Medicine'],
    applyUrl: 'https://online-inspire.gov.in',
    tags: ['Science', 'Merit-Based', 'DST', 'Premium'],
    isNational: true,
  },
  {
    id: 'kvpy',
    name: 'KVPY – Kishore Vaigyanik Protsahan Yojana',
    sponsoringOrg: 'Indian Institute of Science (IISc), Bengaluru',
    amount: 84000,
    amountLabel: '₹5,000–₹7,000/month',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 75,
    maxIncome: 999999999,
    classLevel: ['11', '12', 'UG'],
    deadline: '2026-08-31',
    description: 'Fellowship to encourage students with aptitude for research to take up careers in basic sciences.',
    eligibility: ['Class 11/12/1st yr UG', 'Min 75% in Science (60% for SC/ST/PwD)', 'Pass KVPY aptitude test'],
    applyUrl: 'https://kvpy.iisc.ac.in',
    tags: ['Research', 'Science', 'Fellowship', 'IISc'],
    isNational: true,
  },
  {
    id: 'central-sector',
    name: 'Central Sector Scheme of Scholarships',
    sponsoringOrg: 'Ministry of Education, GoI',
    amount: 20000,
    amountLabel: '₹10,000–₹20,000/year',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 80,
    maxIncome: 450000,
    classLevel: ['UG', 'PG'],
    deadline: '2026-11-30',
    description: 'Merit-based scholarship for college students in top 20 percentile of their board exams.',
    eligibility: ['Top 20 percentile in Class 12 board', 'Income < ₹4.5L/yr', 'Regular college student'],
    applyUrl: 'https://scholarships.gov.in',
    tags: ['Merit', 'Central Govt', 'College'],
    isNational: true,
  },
  {
    id: 'pragati-aicte',
    name: 'AICTE Pragati Scholarship for Girls',
    sponsoringOrg: 'All India Council for Technical Education (AICTE)',
    amount: 50000,
    amountLabel: '₹50,000/year',
    category: ['All'],
    gender: 'Female',
    state: 'All',
    minMarks: 60,
    maxIncome: 800000,
    classLevel: ['UG'],
    deadline: '2026-09-30',
    description: 'For girl students in AICTE approved technical institutions to encourage female participation in tech education.',
    eligibility: ['Female students only', 'AICTE approved institution', 'Income < ₹8L/yr', 'Max 2 girls per family'],
    applyUrl: 'https://www.aicte-india.org',
    tags: ['Girls Only', 'Technical', 'AICTE', 'Engineering'],
    isNational: true,
  },
  {
    id: 'saksham-aicte',
    name: 'AICTE Saksham Scholarship (PwD)',
    sponsoringOrg: 'All India Council for Technical Education (AICTE)',
    amount: 50000,
    amountLabel: '₹50,000/year',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 60,
    maxIncome: 800000,
    classLevel: ['UG'],
    deadline: '2026-09-30',
    description: 'Scholarship for differently-abled students pursuing technical education for inclusive growth.',
    eligibility: ['PwD student (40%+ disability)', 'AICTE approved institution', 'Income < ₹8L/yr'],
    applyUrl: 'https://www.aicte-india.org',
    tags: ['PwD', 'Disability', 'Technical', 'AICTE'],
    isNational: true,
  },
  {
    id: 'pm-yasasvi',
    name: 'PM YASASVI Scholarship',
    sponsoringOrg: 'Ministry of Social Justice & Empowerment',
    amount: 125000,
    amountLabel: '₹75,000–₹1.25L/year',
    category: ['OBC', 'EWS'],
    gender: 'All',
    state: 'All',
    minMarks: 0,
    maxIncome: 250000,
    classLevel: ['9', '10', '11', '12'],
    deadline: '2026-09-15',
    description: 'PM Young Achievers Scholarship for OBC/EWS students in top schools across India.',
    eligibility: ['OBC/EWS category', 'Class 9–12', 'Income < ₹2.5L/yr', 'Must qualify PM-YASASVI test'],
    applyUrl: 'https://yet.nta.ac.in',
    tags: ['School Level', 'OBC', 'EWS', 'PM Scheme'],
    isNational: true,
  },
  {
    id: 'nmms',
    name: 'National Means-cum-Merit Scholarship (NMMS)',
    sponsoringOrg: 'Ministry of Education, GoI',
    amount: 12000,
    amountLabel: '₹12,000/year',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 55,
    maxIncome: 150000,
    classLevel: ['9', '10', '11', '12'],
    deadline: '2026-08-31',
    description: 'Arrest dropout at Class 8 level and encourage meritorious students of economically weaker sections.',
    eligibility: ['Class 9 students', 'Income < ₹1.5L/yr', 'Min 55% in Class 7 (50% for SC/ST)', 'Pass NMMS State Exam'],
    applyUrl: 'https://scholarships.gov.in',
    tags: ['School', 'Merit-cum-Means', 'Class 9–12'],
    isNational: true,
  },
  {
    id: 'rgf-ugc',
    name: 'Rajiv Gandhi National Fellowship (SC/ST)',
    sponsoringOrg: 'University Grants Commission (UGC)',
    amount: 225600,
    amountLabel: '₹14,000–₹18,800/month',
    category: ['SC', 'ST'],
    gender: 'All',
    state: 'All',
    minMarks: 55,
    maxIncome: 999999999,
    classLevel: ['PG'],
    deadline: '2026-07-31',
    description: 'Fellowship for SC/ST students pursuing MPhil and PhD at Indian universities.',
    eligibility: ['SC/ST candidates', 'MPhil/PhD program', 'NET/SLET qualified preferred', 'Age < 40 years'],
    applyUrl: 'https://ugc.ac.in',
    tags: ['Research', 'Fellowship', 'PhD', 'UGC', 'Premium'],
    isNational: true,
  },
  {
    id: 'begum-hazrat',
    name: 'Begum Hazrat Mahal National Scholarship',
    sponsoringOrg: 'Maulana Azad Education Foundation',
    amount: 12000,
    amountLabel: '₹5,000–₹12,000/year',
    category: ['All'],
    gender: 'Female',
    state: 'All',
    minMarks: 50,
    maxIncome: 200000,
    classLevel: ['9', '10', '11', '12'],
    deadline: '2026-09-30',
    description: 'Scholarship for meritorious girls from minority communities to continue school education.',
    eligibility: ['Girl students from minority communities', 'Class 9–12', 'Min 50% marks', 'Income < ₹2L/yr'],
    applyUrl: 'https://maef.nic.in',
    tags: ['Girls', 'Minority', 'School Level'],
    isNational: true,
  },
  {
    id: 'tata-pankh',
    name: 'Tata Capital Pankh Scholarship',
    sponsoringOrg: 'Tata Capital Limited',
    amount: 50000,
    amountLabel: 'Up to ₹50,000/year',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 60,
    maxIncome: 400000,
    classLevel: ['UG'],
    deadline: '2026-09-15',
    description: 'Tata Capital\'s flagship scholarship for underprivileged students pursuing graduation in any stream.',
    eligibility: ['1st year UG students', 'Income < ₹4L/yr', 'Min 60% in Class 12', 'Recognized college'],
    applyUrl: 'https://tatacapital.com/pankh',
    tags: ['Private', 'Tata', 'UG', 'Merit-cum-Means'],
    isNational: true,
  },
  {
    id: 'hdfc-ecs',
    name: 'HDFC Bank Parivartan ECS Scholarship',
    sponsoringOrg: 'HDFC Bank Limited',
    amount: 75000,
    amountLabel: 'Up to ₹75,000/year',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 55,
    maxIncome: 250000,
    classLevel: ['UG', 'PG'],
    deadline: '2026-10-15',
    description: 'HDFC Bank\'s scholarship for meritorious students from economically weaker sections in higher education.',
    eligibility: ['UG/PG students', 'Income < ₹2.5L/yr', 'Min 55%', 'No other scholarship'],
    applyUrl: 'https://hdfcbank.com/parivartan',
    tags: ['Private', 'HDFC', 'Banking', 'UG', 'PG'],
    isNational: true,
  },
  {
    id: 'reliance-foundation',
    name: 'Reliance Foundation Scholarships',
    sponsoringOrg: 'Reliance Foundation',
    amount: 200000,
    amountLabel: 'Up to ₹2L/year',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 60,
    maxIncome: 250000,
    classLevel: ['UG', 'PG'],
    deadline: '2026-12-31',
    description: 'Scholarship for students in top NIRF-ranked colleges pursuing STEM and social sciences.',
    eligibility: ['Top 100 NIRF colleges', 'Income < ₹2.5L/yr', 'Min 60%', 'UG/PG courses'],
    applyUrl: 'https://reliancefoundation.org/scholarships',
    tags: ['Private', 'Reliance', 'STEM', 'Premium'],
    isNational: true,
  },
  {
    id: 'wipro-cares',
    name: 'Wipro Cares Scholarship',
    sponsoringOrg: 'Wipro Limited',
    amount: 30000,
    amountLabel: '₹30,000/year',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 60,
    maxIncome: 300000,
    classLevel: ['UG'],
    deadline: '2026-08-15',
    description: 'Wipro\'s CSR scholarship for engineering and science students from economically weaker sections.',
    eligibility: ['Engineering/Science UG', 'Income < ₹3L/yr', 'Min 60% in Class 12', '1st or 2nd year'],
    applyUrl: 'https://wipro.com/sustainability',
    tags: ['Private', 'Wipro', 'Engineering', 'IT'],
    isNational: true,
  },
  {
    id: 'up-sc-girl',
    name: 'UP SC/ST Girl Students Scholarship',
    sponsoringOrg: 'Social Welfare Department, Uttar Pradesh',
    amount: 18000,
    amountLabel: '₹18,000/year',
    category: ['SC', 'ST'],
    gender: 'Female',
    state: 'Uttar Pradesh',
    minMarks: 45,
    maxIncome: 200000,
    classLevel: ['9', '10', '11', '12', 'UG'],
    deadline: '2026-11-30',
    description: 'Uttar Pradesh scholarship for SC/ST girl students to encourage female literacy and higher education.',
    eligibility: ['SC/ST girl from UP', 'UP school/college', 'Income < ₹2L/yr', 'Min 45% marks'],
    applyUrl: 'https://scholarship.up.gov.in',
    tags: ['UP', 'Girls', 'SC/ST', 'State'],
    isNational: false,
  },
  {
    id: 'rajasthan-sc',
    name: 'Rajasthan SC/ST Scholarship Scheme',
    sponsoringOrg: 'Social Justice & Empowerment Dept., Rajasthan',
    amount: 25000,
    amountLabel: '₹25,000/year',
    category: ['SC', 'ST'],
    gender: 'All',
    state: 'Rajasthan',
    minMarks: 50,
    maxIncome: 250000,
    classLevel: ['9', '10', '11', '12', 'UG', 'PG'],
    deadline: '2026-10-15',
    description: 'Rajasthan state scholarship for SC/ST students from school to university level.',
    eligibility: ['SC/ST students from Rajasthan', 'Studying in Rajasthan', 'Income < ₹2.5L/yr', 'Min 50% marks'],
    applyUrl: 'https://sje.rajasthan.gov.in',
    tags: ['Rajasthan', 'SC/ST', 'State'],
    isNational: false,
  },
  {
    id: 'karnataka-bc',
    name: 'Karnataka Backward Classes Scholarship',
    sponsoringOrg: 'Backward Classes Welfare Dept., Karnataka',
    amount: 20000,
    amountLabel: '₹20,000/year',
    category: ['OBC'],
    gender: 'All',
    state: 'Karnataka',
    minMarks: 50,
    maxIncome: 150000,
    classLevel: ['UG', 'PG'],
    deadline: '2026-09-30',
    description: 'Karnataka government scholarship for students from backward classes in higher education.',
    eligibility: ['OBC/BC from Karnataka', 'Karnataka college', 'Income < ₹1.5L/yr', 'Min 50%'],
    applyUrl: 'https://bcwd.kar.nic.in',
    tags: ['Karnataka', 'OBC', 'State'],
    isNational: false,
  },
  {
    id: 'gujarat-merit',
    name: 'Gujarat State Merit Scholarship',
    sponsoringOrg: 'Education Department, Govt. of Gujarat',
    amount: 15000,
    amountLabel: '₹15,000/year',
    category: ['All'],
    gender: 'All',
    state: 'Gujarat',
    minMarks: 80,
    maxIncome: 600000,
    classLevel: ['11', '12', 'UG'],
    deadline: '2026-10-01',
    description: 'Gujarat merit scholarship for academically outstanding students to encourage excellence.',
    eligibility: ['Students from Gujarat', 'Min 80% marks', 'Income < ₹6L/yr', 'Gujarat recognized institution'],
    applyUrl: 'https://gujaratscholarship.gujarat.gov.in',
    tags: ['Gujarat', 'Merit', 'State'],
    isNational: false,
  },
  {
    id: 'vidyadhan',
    name: 'Vidyadhan Scholarship',
    sponsoringOrg: 'Sarojini Damodaran Foundation',
    amount: 50000,
    amountLabel: '₹10,000–₹50,000/year',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 70,
    maxIncome: 200000,
    classLevel: ['11', '12', 'UG'],
    deadline: '2026-05-31',
    description: 'NGO scholarship for students from economically disadvantaged backgrounds with strong character.',
    eligibility: ['Income < ₹2L/yr', 'Min 70% in Class 10', 'Strong extracurricular', 'Genuine financial need'],
    applyUrl: 'https://vidyadhan.org',
    tags: ['NGO', 'Merit-cum-Means', 'Multi-level'],
    isNational: true,
  },
  {
    id: 'jindal-foundation',
    name: 'Sitaram Jindal Foundation Scholarship',
    sponsoringOrg: 'Sitaram Jindal Foundation',
    amount: 36000,
    amountLabel: 'Up to ₹3,000/month',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 55,
    maxIncome: 250000,
    classLevel: ['10', '11', '12', 'UG', 'PG'],
    deadline: '2026-09-30',
    description: 'Wide-reach scholarship for economically weaker students across all education levels.',
    eligibility: ['Min 55% marks', 'Income < ₹2.5L/yr', 'Recognized institution', 'No central govt. scholarship'],
    applyUrl: 'https://sjfoundation.com',
    tags: ['Private Foundation', 'Multi-level', 'Monthly Stipend'],
    isNational: true,
  },
  {
    id: 'swami-vivekanand-mp',
    name: 'Swami Vivekananda Scholarship (MP)',
    sponsoringOrg: 'MP Tribal Welfare Department',
    amount: 72000,
    amountLabel: 'Up to ₹6,000/month',
    category: ['All'],
    gender: 'All',
    state: 'Madhya Pradesh',
    minMarks: 75,
    maxIncome: 600000,
    classLevel: ['UG', 'PG'],
    deadline: '2026-11-01',
    description: 'MP scholarship for meritorious students pursuing higher studies in top national institutions.',
    eligibility: ['MP domicile', 'Top national institutions (IITs, IIMs)', 'Income < ₹6L/yr', 'Min 75%'],
    applyUrl: 'https://scholarshipportal.mp.nic.in',
    tags: ['Madhya Pradesh', 'IIT/IIM', 'State', 'Premium'],
    isNational: false,
  },
  {
    id: 'wb-oshc',
    name: 'West Bengal OSHC Scholarship',
    sponsoringOrg: 'West Bengal Government',
    amount: 36000,
    amountLabel: '₹36,000/year',
    category: ['SC', 'ST', 'OBC'],
    gender: 'All',
    state: 'West Bengal',
    minMarks: 50,
    maxIncome: 200000,
    classLevel: ['UG', 'PG'],
    deadline: '2026-10-31',
    description: 'West Bengal scholarship for SC/ST/OBC students in higher education.',
    eligibility: ['SC/ST/OBC from West Bengal', 'WB recognized institution', 'Income < ₹2L/yr', 'Min 50%'],
    applyUrl: 'https://oasis.wb.gov.in',
    tags: ['West Bengal', 'SC/ST/OBC', 'State'],
    isNational: false,
  },
  {
    id: 'iocl-scholarship',
    name: 'IndianOil Educational Scholarship',
    sponsoringOrg: 'IndianOil Corporation Limited (IOCL)',
    amount: 30000,
    amountLabel: '₹1,000–₹3,000/month',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 60,
    maxIncome: 100000,
    classLevel: ['11', '12', 'UG'],
    deadline: '2026-08-31',
    description: 'IOCL scholarship for engineering, medical, MBA, and general degree students from economically weaker families.',
    eligibility: ['Indian students', 'Income < ₹1L/yr', 'Min 60% marks', 'Applied within 1st year'],
    applyUrl: 'https://iocl.com/ScholarshipScheme.aspx',
    tags: ['PSU', 'IOCL', 'Engineering', 'Medical'],
    isNational: true,
  },
  {
    id: 'kotak-kanya',
    name: 'Kotak Kanya Scholarship',
    sponsoringOrg: 'Kotak Education Foundation',
    amount: 150000,
    amountLabel: 'Up to ₹1.5L/year',
    category: ['All'],
    gender: 'Female',
    state: 'All',
    minMarks: 85,
    maxIncome: 330000,
    classLevel: ['UG'],
    deadline: '2026-08-15',
    description: 'Premium scholarship for girl students with 85%+ in Class 12 pursuing first year of professional degree.',
    eligibility: ['Girl students only', 'Min 85% in Class 12', 'Income < ₹3.3L/yr', '1st yr Engg/Medical/Law/CA/CS'],
    applyUrl: 'https://kotakeducation.org',
    tags: ['Girls', 'Private', 'Kotak', 'Professional', 'Merit'],
    isNational: true,
  },
  {
    id: 'dte-maharashtra',
    name: 'GOI Post-Matric Scholarship (Maharashtra)',
    sponsoringOrg: 'DTE Maharashtra',
    amount: 40000,
    amountLabel: '₹40,000/year',
    category: ['SC', 'OBC', 'EWS'],
    gender: 'All',
    state: 'Maharashtra',
    minMarks: 45,
    maxIncome: 250000,
    classLevel: ['11', '12', 'UG', 'PG'],
    deadline: '2026-11-30',
    description: 'Maharashtra post-matric scholarship for SC, OBC, and EWS students in technical and professional education.',
    eligibility: ['SC/OBC/EWS from Maharashtra', 'Income < ₹2.5L/yr', 'DTE approved institution', 'Min 45%'],
    applyUrl: 'https://mahadbt.maharashtra.gov.in',
    tags: ['Maharashtra', 'SC/OBC/EWS', 'Technical', 'State'],
    isNational: false,
  },
  {
    id: 'nab-scholarship',
    name: 'NAB Scholarship – Visually Impaired',
    sponsoringOrg: 'National Association for the Blind (NAB)',
    amount: 15000,
    amountLabel: '₹15,000/year',
    category: ['All'],
    gender: 'All',
    state: 'All',
    minMarks: 50,
    maxIncome: 200000,
    classLevel: ['9', '10', '11', '12', 'UG', 'PG'],
    deadline: '2026-10-31',
    description: 'Scholarship for visually impaired students from economically weaker sections to continue education.',
    eligibility: ['Visually impaired (certified)', 'Income < ₹2L/yr', 'Min 50% marks', 'Recognized institution'],
    applyUrl: 'https://nabin.org',
    tags: ['PwD', 'Visual Impairment', 'NGO', 'All Levels'],
    isNational: true,
  },
  {
    id: 'maha-eklavya',
    name: 'Eklavya Scholarship for Tribal Students',
    sponsoringOrg: 'Maharashtra Tribal Development Department',
    amount: 40000,
    amountLabel: '₹40,000/year',
    category: ['ST'],
    gender: 'All',
    state: 'Maharashtra',
    minMarks: 60,
    maxIncome: 200000,
    classLevel: ['11', '12', 'UG'],
    deadline: '2026-10-31',
    description: 'Maharashtra scholarship for tribal students to pursue higher education and professional courses.',
    eligibility: ['ST students from Maharashtra', 'Min 60%', 'Income < ₹2L/yr', 'MH recognized institution'],
    applyUrl: 'https://mahadbt.maharashtra.gov.in',
    tags: ['Maharashtra', 'Tribal', 'State'],
    isNational: false,
  },
];

export const stateList = [
  'All States', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
  'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
  'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra',
  'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Delhi', 'Chandigarh',
  'Jammu & Kashmir', 'Ladakh',
];

export const categoryList = ['All', 'SC', 'ST', 'OBC', 'EWS', 'General'];
export const genderList = ['All', 'Female', 'Male'];
export const classList = ['All', '9', '10', '11', '12', 'UG', 'PG'];
export const incomeRanges = [
  { label: 'Any Income', value: 999999999 },
  { label: 'Below ₹1 Lakh', value: 100000 },
  { label: 'Below ₹2 Lakhs', value: 200000 },
  { label: 'Below ₹2.5 Lakhs', value: 250000 },
  { label: 'Below ₹4.5 Lakhs', value: 450000 },
  { label: 'Below ₹8 Lakhs', value: 800000 },
];
